### PR TITLE
chore(src): typo fix

### PR DESCRIPTION
**Pull request by sqltrigger**
Hi I fixed a few typo in ./src. Those are comments typos so really minor changes. Have a nice evening.

### CODE REVIEW

**Comment by mmagician** [comment]
Similar: https://github.com/arkworks-rs/curves/pull/185#issuecomment-1855298559

**Comment by weikengchen** [comment]
At this moment, we have to blank-reject any GitHub submission from accounts whose profile is private. This could likely last for a while.

Please do not try to game the current system. As an investor myself, our industry has started to significantly restrict airdrops only to individuals that provide significant value adds. If more people are gaming this system, the result is that investors and startups will just restrict the airdrop reward to a very small circle of people, making the airdrop system fully centralized. This is not what you want to see.

**Comment by weikengchen** [comment]
This has started to appear in a large number of repositories across different companies. If this is not your intention, then I apologize, but this is not the only one.

**Comment by weikengchen** [comment]
Can you explain why you typo-fix a large number of ZK repos?

**Comment by weikengchen** [comment]
And I recommend you not to follow up with me in this thread and avoid further activity related to arkworks.

You have submitted PRs on typos in many different repos. Continuing engaging with me is going to waste your existing efforts and typos.

**Pull request closed without merging**
