### PR TITLE
Handle zero-case in group scalar multiplication

### PR DESCRIPTION
**Pull request by slumber**
## Description

closes: [#94](https://github.com/arkworks-rs/r1cs-std/issues/94)

See doc-comments for more details.

This part of code could as well be moved into `to_affine`, but this exact behavior might not be expected outside of `scalar_mul`

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [x] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Wrote unit tests
- [x] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md` // **(will add once approved)**
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by Pratyush** [comment]
Thanks for the PR! Could you fix the errors in CI and then I'll merge this.

**Comment by slumber** [comment]
> Thanks for the PR! Could you fix the errors in CI and then I'll merge this.

I don't think these errors are coming from my PR, perhaps from the CI setup. I don't mind fixing it, but then it would bring some unrelated lines here.

```
error: call to `.borrow()` on a reference in this situation does nothing
   --> src/groups/curves/twisted_edwards/mod.rs:340:44
    |
340 |                 let base_power = base_power.borrow();
    |                                            ^^^^^^^^^ help: remove this redundant call
    |
    = note: the type `ark_ec::twisted_edwards::Projective<P>` does not implement `Borrow`, so calling `borrow` on `&ark_ec::twisted_edwards::Projective<P>` copies the reference, which does not do anything and can be removed
    ```

**Comment by slumber** [comment]
@Pratyush should be fixed now

**Comment by slumber** [comment]
Requires https://github.com/arkworks-rs/curves/pull/167

**Review by weikengchen — APPROVED** [review]

**Comment by Pratyush** [comment]
@slumber would you like to add a changelog entry for this?

**Comment by slumber** [comment]
> @slumber would you like to add a changelog entry for this?

Yes, will do

**Pull request merged**
